# Site details
title: SERC Git Labs
description: Course notes and learning materials for teaching and learning Git and GitHub.
url: https://serc-git-labs.github.io
gh_repository: https://github.com/SERC-Git-Labs/serc-git-labs.github.io
gh_org: https://github.com/SERC-Git-Labs
moodle_page: <link-to-course-moodle-page>

# Theme
theme: just-the-docs
color_scheme: serc

# Footer content
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

mermaid:
  version: "11.5.0"

kramdown:
  syntax_highlighter: rouge
  parse_block_html: false

callouts:
  highlight:
    color: yellow
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  solution:
    title: Solution
    color: green
callouts_opacity: 0.1

# Slide defaults
slides:
  theme: simple
  transition: none

plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
